ping:
  get:
    tags: [App]
    summary: Ping API
    description: >
      Ping endpoint to check server availability and update admin connection status.
      The extension should send its version in the `x-ext-version` header.
    security:
      - XAuthEmail: []
        XAuthPassword: []
        XClientId: []
    parameters:
      - in: header
        name: x-ext-version
        schema:
          type: string
        required: false
        description: Extension version, e.g. "1.2.3" or "v1.2.3".
    responses:
      "200":
        description: OK
        content:
          application/json:
            schema:
              type: object
              properties:
                ok: { type: boolean }
                version: { type: string }
      "401":
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: "../components/schemas.yaml#/ErrorResponse"

ping_status:
  get:
    tags: [App]
    summary: Extension ping status
    description: >
      Returns the connection status of the admin and extension version info.
    security:
      - XAuthEmail: []
        XAuthPassword: []
        XClientId: []
    responses:
      "200":
        description: OK
        content:
          application/json:
            schema:
              type: object
              properties:
                ok: { type: boolean }
                connected: { type: boolean }
                extVersion:
                  type: string
                  nullable: true
                versionMismatch:
                  type: boolean
                lastPingAt:
                  type: string
                  format: date-time
                  nullable: true
      "401":
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: "../components/schemas.yaml#/ErrorResponse"
      "403":
        description: Forbidden (session required)
        content:
          application/json:
            schema:
              $ref: "../components/schemas.yaml#/ErrorResponse"

sse:
  get:
    tags: [App]
    summary: Server-Sent Events (logs/progress)
    description: Text/event-stream channel used by the web app.
    responses:
      "200":
        description: Event stream

log:
  post:
    tags: [App]
    summary: Client log upload
    requestBody:
      required: true
      content:
        application/json:
          schema:
            oneOf:
              - type: object
                additionalProperties: true
              - type: array
                items:
                  type: object
                  additionalProperties: true
    responses:
      "204":
        description: Accepted
      "400":
        description: Invalid payload
        content:
          application/json:
            schema:
              $ref: "../components/schemas.yaml#/ErrorResponse"
